version: "3.9"

services:

  scanner_1:
    build: .
    env_file:
      - .env
    volumes:
      - ${PATH_TO_YARA_RULES}:/yara-app/static/yara-rules
  
  scanner_2:
    build: .
    env_file:
      - .env
    volumes:
      - ${PATH_TO_YARA_RULES}:/yara-app/static/yara-rules
  
  scanner_3:
    build: .
    env_file:
      - .env
    volumes:
      - ${PATH_TO_YARA_RULES}:/yara-app/static/yara-rules
  
  scanner_4:
    build: .
    env_file:
      - .env
    volumes:
      - ${PATH_TO_YARA_RULES}:/yara-app/static/yara-rules


  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - scanner_1
      - scanner_2
      - scanner_3
      - scanner_4
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}

    